TestInvest/TestInvest/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from perfiles.views import (SignUpView, SignInView, SignOutView,
                            UpdateProfileView, ProfileView)
from TestInvest import settings
from perfiles import views, views_asset, views_alarm
from django.conf.urls.static import static


def anonymous_required(func):
    def as_view(request, *args, **kwargs):
        redirect_to = kwargs.get('next', settings.LOGIN_REDIRECT_URL)
        if request.user.is_authenticated:
            return redirect(redirect_to)
        response = func(request, *args, **kwargs)
        return response
    return as_view


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.WelcomeView, name='home'),
    url(r'^profile/$', login_required(views.profileView), name='profile'),
    url(r'^signup/$', anonymous_required(SignUpView.as_view()),
        name='sign_up'),
    url(r'^login/$', anonymous_required(SignInView.as_view()),
        name='sign_in'),
    url(r'^logout/$', SignOutView.as_view(), name='sign_out'),
    url(r'^password/$', login_required(views.change_password),
        name='change_password'),
    url(r'^profile/$', ProfileView.as_view(), name='profile'),
    url(r'^update_profile/$', UpdateProfileView.as_view(
        success_url='/profile'), name='update_profile'),
    url(r'^price/$', login_required(views_asset.show_assets), name='price'),
    url(r'^buy/$', login_required(views_asset.show_assets), name='buy'),
    url(r'^wallet/$', login_required(views_asset.show_my_assets), name='wallet'),
    url(r'^salle/$', login_required(views_asset.sell_assets), name='salle'),
    url(r'^transactionhistory/$', login_required(views.mytransactions),
                   name='transaction_history'),
    url(r'^ranking/$', login_required(views.ranking), name='ranking'),
    url(r'^assetshistory/$', login_required(views_asset.assets_history),
        name='assets_history'),
    url(r'^alarm/$', login_required(views_alarm.config_alarm),
                   name='alarm'),
    url(r'^view_alarm/$', login_required(views_alarm.view_alarm),
                   name='view_alarm'),
   url(r'^visibilityinvestments/$', login_required(views.visibility_investments),
                   name='visibility_investments'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

TestInvest/perfiles/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User, AbstractUser
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.validators import MinValueValidator
from django.utils import timezone
from .data_api import (open_jsons, quit_null_assets, open_json_history,
                       get_asset_history)


class CustomUser(AbstractUser):
    '''
    Modelo usuario que reemplaza al tradicional utilizado internamente por
    Django.
    Se le agregan atributos como avatar y moneda virtual.
    '''
    avatar = models.ImageField(upload_to='perfiles/',
                               default='perfiles/default.jpg')
    virtual_money = models.FloatField(
        validators=[MinValueValidator(0.0)], blank=None, default=1000
        )

    def __str__(self):
        return self.email

    def calculate_capital(assets, my_assets, virtual_money):
        '''
        calculate_capital: Calcula el capital del usuario logueado tomando
        los activos que tiene y su cotización actual más su dinero virtual.
        '''
        cap = 0
        for name, data in assets:
            for asset in my_assets:
                if (asset.name == name[1] and data['sell'] is not None):
                    cap += asset.total_amount * data['sell']
        cap += virtual_money
        return cap

    def update_money_user(request, total_amount, data, virtual_money):
        """ update_money_user: Actualiza el dinero virtual del usuario.
            update_money_user = update_money_user +/- total de activo en
            operacion multiplicado la cotizacion
        """
        if request.get_full_path() == '/buy/':
            virtual_money -= total_amount * data
        else:
            virtual_money += total_amount * data
        request.user.virtual_money = virtual_money
        request.user.save()

    def cons_ranking():
        """ cons_ranking: Brinda la lista de puestos en el ranking de los usuarios
        con su capital.
        [[posicion, nombre usuario, capital]]
        """
        assets = open_jsons()
        dict_cap = {}
        users = CustomUser.objects.all()
        i = 1
        ranking = []
        for user in users:
            assets_users = UserAsset.objects.filter(user=user.id)
            capital = CustomUser.calculate_capital(assets, assets_users,
                                                   user.virtual_money)
            dict_cap.update({user.username: capital})
        dict_items = dict_cap.items()
        list_cap = sorted(dict_items, key=lambda x: x[1], reverse=True)
        total_user = CustomUser.objects.count()
        for i in range(total_user):
            ranking.append((i+1,) + list_cap[i])
        return ranking

    def rank_virtualm(request):
        """ rank_virtualm: Muestra la posicion en el ranking del usuario logueado.
        """
        ranking = CustomUser.cons_ranking()
        pos_rank = 0
        for rank in ranking:
            if request.user.username == rank[1]:
                request.user.pos_ranking = rank[0]
                request.user.save()
        return request.user.pos_ranking


@receiver(post_save, sender=User)
def crear_usuario_perfil(sender, instance, created, **kwargs):
    if created:
        Perfil.objects.create(usuario=instance)


@receiver(post_save, sender=User)
def guardar_usuario_perfil(sender, instance, **kwargs):
    instance.perfil.save()


class UserAsset(models.Model):
    '''
    Modelo de activo para el usuario.
    Se forma una relación varios - uno con el usuario registrado en el sistema.
    '''
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    type_asset = models.CharField(max_length=30)
    total_amount = models.PositiveIntegerField(blank=None)
    old_unit_value = models.FloatField(
        validators=[MinValueValidator(0.0)], blank=None)
    visibility = models.BooleanField(default=False)

    def addAsset(request, name, total_amount, type_asset, old_unit_value,
                 visibility):
        """ addAsset: Agrega un activo a la Base de Datos.
        """
        asset = UserAsset.objects.create(
                  user_id=request.user.id, name=name,
                  total_amount=total_amount,
                  type_asset=type_asset, old_unit_value=old_unit_value,
                  visibility=visibility)
        asset.save()
        return asset

    def update_asset(asset, total_amount, data, visibility):
        """ update_asset: Actualiza la cantidad de un activo.
        """
        asset.total_amount += total_amount
        asset.old_unit_value = data
        asset.visibility = visibility
        asset.save()


class Transaction(models.Model):
    '''
    Modelo de transacción para cuando un usuario registrado y logueado realiza
    una compra o una venta de un activo.
    '''
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    user_asset = models.ForeignKey(UserAsset, on_delete=models.CASCADE)
    type_transaction = models.CharField(max_length=30)
    value_buy = models.FloatField(
        validators=[MinValueValidator(0.0)], blank=None
        )
    value_sell = models.FloatField(
        validators=[MinValueValidator(0.0)], blank=None
        )
    amount = models.PositiveIntegerField(blank=None)
    date = models.DateTimeField(max_length=50)

    def addTransaction(request, value_buy, value_sell, total_amount,
                       user_asset_id):
        """ addTransaction: Agrega una transaccion a la Base de Datos.
        """
        if request.get_full_path() == '/buy/':
            type_t = str("compra")
        else:
            type_t = str("venta")
        transaction = Transaction.objects.create(user_id=request.user.id,
                                                 user_asset_id=user_asset_id,
                                                 value_buy=value_buy,
                                                 value_sell=value_sell,
                                                 amount=total_amount,
                                                 date=timezone.now(),
                                                 type_transaction=type_t)
        transaction.save()
        return transaction


class Alarm(models.Model):
    '''
    Modelo de alarma. Se relaciona con varios - uno con el usuario registrado.
    '''
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    name_asset = models.CharField(max_length=30)
    type_alarm = models.CharField(max_length=30)
    type_quote = models.CharField(max_length=30)
    type_umbral = models.CharField(max_length=30)
    previous_quote = models.FloatField(
        validators=[MinValueValidator(0.0)], blank=None)
    umbral = models.FloatField(
        validators=[MinValueValidator(0.0)], blank=None)
    email_send = models.BooleanField(default=False)

    def addAlarm(request, type_quote, type_umbral,
                 umbral, previous_quote, name_asset):
        '''
        addAlarm: Crea y guarda una alarma en la base de datos.
        '''
        alarm = Alarm.objects.create(
                    user_id=request.user.id, name_asset=name_asset,
                    type_alarm="high", type_quote=type_quote,
                    type_umbral=type_umbral, umbral=umbral,
                    previous_quote=previous_quote)
        alarm.save()
        return alarm

TestInvest/perfiles/views.py
# -- coding: utf-8 --
from __future__ import unicode_literals
from django.shortcuts import (render, render_to_response, get_object_or_404,
                              redirect)
from django.contrib.auth import login, authenticate, update_session_auth_hash
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import CreateView, TemplateView, UpdateView
from django.contrib.auth.forms import PasswordChangeForm
from .forms import SignUpForm, UpdateProfileForm, Visibility
from django.contrib import messages
from .models import CustomUser, UserAsset, Transaction
from .data_api import open_jsons, quit_null_assets
from .views_alarm import get_data_of_alarm
import threading
import time
from django.template import RequestContext
from datetime import datetime
from django.core.mail import EmailMessage, send_mail
from django.contrib.auth.decorators import login_required


class SignUpView(CreateView):
    model = CustomUser
    form_class = SignUpForm
    template_name = 'perfiles/signup.html'

    def form_valid(self, form):
        form.save()
        usuario = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        usuario = authenticate(username=usuario, password=password)
        return render(self.request, 'perfiles/signup.html', {'form': form})


def WelcomeView(request):
    """ welcomeView: Envia a la pagina de inicio, con el puesto en el ranking
        y el dinero liquido del usuario logueado, o para que inicie sesion o
        se registre.
    """
    if request.user.is_authenticated:
        return render(request, 'perfiles/home.html',
                      {'pos_ranking': CustomUser.rank_virtualm(request)})
    else:
        return render(request, 'perfiles/home.html')


class ProfileView(TemplateView):
    template_name = 'perfiles/profile.html'


def profileView(request):
    """ profileView: Muestra en la pagina de perfil el puesto en el ranking y
        el dinero liquido del usuario logueado
    """
    pos_ranking = CustomUser.rank_virtualm(request)
    return render(request, 'perfiles/profile.html',
                  {'pos_ranking': pos_ranking})


def change_password(request):
    '''change_password: Cambia la contraseña del usuario logueado
    '''
    pos_ranking = CustomUser.rank_virtualm(request)
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'perfiles/change_password.html',
                  {'form': form, 'pos_ranking': pos_ranking})


class SignInView(LoginView):
    template_name = 'perfiles/login.html'


class SignOutView(LogoutView):
    pass


class UpdateProfileView(UpdateView):
    model = CustomUser
    template_name = 'perfiles/update_profile.html'
    form_class = UpdateProfileForm

    def get_object(self):
        """
        get_object: Retorna la información del usuario logueado. En caso de no
        encontrarlo, devuelve error 404 not found.
        """
        return get_object_or_404(CustomUser, pk=self.request.user.id)


def addOperation(request, assets_user, nametype, name_form,
                 total_amount, sell, buy, virtual_money, visibility):
    """ addOperation: Agrega una operacion de compra a la base de datos.
    """
    if assets_user.exists():
        for asset in assets_user:
            if (nametype[1] == asset.name):
                UserAsset.update_asset(asset, total_amount, sell, visibility)
                transaction = Transaction.addTransaction(
                  request, sell, buy, total_amount, asset.id)
                CustomUser.update_money_user(
                  request, total_amount, sell, virtual_money)
    elif (nametype[1] == name_form):
        asset_user = UserAsset.addAsset(request, name_form, total_amount,
                                        nametype[0], buy, visibility)
        transaction = Transaction.addTransaction(
          request, sell, buy, total_amount, asset_user.id)
        CustomUser.update_money_user(
          request, total_amount, buy, virtual_money)
    return virtual_money


def mytransactions(request):
    """ mytransactions: devuelve las transacciones del usuario logeado.
    """
    pos_ranking = CustomUser.rank_virtualm(request)
    my_transactions = Transaction.objects.filter(user=request.user.id)
    my_transactions = my_transactions.order_by('-date')
    return render_to_response(
      'perfiles/transaction_history.html', {'my_transactions': my_transactions,
                                            'user': request.user,
                                            'pos_ranking': pos_ranking})


def ranking(request):
    """ ranking: Renderiza la lista.
    """
    pos_ranking = CustomUser.rank_virtualm(request)
    list_cap = CustomUser.cons_ranking()
    users = CustomUser.objects.all()
    return render_to_response('perfiles/see_ranking.html',
                              {'lista_capital': list_cap,
                               'user': request.user,
                               'pos_ranking': pos_ranking})


def visibility_investments(request):
    """visibility_investments: Renderiza las transacciones visibles.
    """
    pos_ranking = CustomUser.rank_virtualm(request)
    ranking = CustomUser.cons_ranking()
    all_assets = open_jsons()
    assets_a = quit_null_assets(all_assets)
    investments_v = UserAsset.objects.filter(visibility=True,
                                             total_amount__gt=0)
    datas = []
    for invest in investments_v:
        assets = UserAsset.objects.filter(user_id=invest.user_id,
                                          name=invest.name)
        for asset in assets:
            ult_trans = Transaction.objects.filter(user_id=invest.user_id,
                                                   type_transaction='compra',
                                                   user_asset_id=asset.id)
            ult_trans = ult_trans.last()
            datas.append([invest.user_id, asset.name, ult_trans.date,
                          ult_trans.value_sell])
    return render_to_response('perfiles/visibility_investments.html',
                              {'user': request.user,
                               'investments_v': investments_v,
                               'ranking': ranking, 'pos_ranking': pos_ranking,
                               'datas': datas, 'assets': assets_a})


'''Funciones para consultar los cambios en los datos de la API y enviar mail
   al usuario que configuró su alarma
'''


def consult_alarm_forever():
    '''consult_alarm_forever: Llama a la función get_data_of_alarm cada 15 segundos
    '''
    while True:
        get_data_of_alarm()
        time.sleep(15)


#def hilo():
    '''hilo: Se define como hilo principal a la función consult_alarm_forever()
    '''
 #   hilo = threading.Thread(target=consult_alarm_forever)
  #  hilo.setDaemon(True)
   # hilo.start()


#hilo()
'''hilo(): se debe ejecutar al iniciar el programa'''

TestInvest/perfiles/templates/perfiles/assets_history.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/assetshistory.css' %}">
<script src="{% static 'js/assetshistory.js' %}"></script>
  <div id="back0">
    <div id="back">
      <div id="container" class="container">
        <div>
          {% if assets or is_history %}
           {% include 'perfiles/tab_price.html' %}
           <script>document.getElementById("nameC").innerHTML = "Activos Disponibles";</script>
          {% else %}
           <h1 id="mj_not_assets">No hay activos disponibles para consultar historial</h1>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
  <div class="popup" id="myPopup">
    <form class="form" action="{% url 'assets_history' %}" method="POST"
          id="assets_history_form" onsubmit="name_enable(event)">
      <input type="button" class="btn cancel" onclick="closePop()" value="x"/>
      <b>Elija desde y hasta cuando quedra ver el historial del activo</b><br><br>
      {% csrf_token %}
      {{ form.as_p }}
      <button class="submit">Ver historial</button>
    </form>
  </div>
  {% if is_history %}
    {% if history %}
    <center><h2 id="mj_graph"></h2></center>
    <div style="width:95%; height:95%; position:relative; left:1%;z-index:-1" id="graph">
    </div>
    <center>
    <h2>Historial de {{name_asset}}</h2><br>
    <table>
      <thead>
        <tr><th>Fecha</th><th>Valor de Compra</th><th>Valor de Venta</th></tr>
      </thead>
      <tbody>
       {% for data in history %}
        <tr><td>{{ data.0 }}</td><td>{{ data.1 }}</td><td>{{ data.2 }}</td></tr>
      {% endfor %}
      </tbody>
    </table>
    {% else %}
      <center><h2>No hay datos historicos</h2>
      <h2>para el archivo seleccionado</h2>
    {% endif %}
   <html>
     <head>
      <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
      <script type="text/javascript">
        document.getElementById("prices").style.display = "none";
        google.charts.load('current', {'packages':['corechart']});
        google.charts.setOnLoadCallback(drawChart);
        document.getElementById('mj_graph').innerHTML= "Grafica de valores";
        function drawChart() {
          //drawChart: Toma las fechas y valores dados por el back y dibuja el grafico.
          var djangoData = {{ grap|safe }};
          var data = google.visualization.arrayToDataTable(djangoData);
          var chart = new google.visualization.LineChart(document.getElementById('graph'));
          chart.draw(data);
        };
      </script>
    </head>
  </html>
  <script>
    document.getElementById("nameC").innerHTML = "";
  </script>
   {% else %}
  {% endif %}
  <script>
  function put_values_on_the_form() {
    //put_values_on_the_form: Completa el formulario de acuerdo a lo elejido por el usuario y habilita la funcion enableDiv.
    document.getElementById("id_name").value = localStorage.name;
    document.getElementById("id_name").disabled = true;
    setTimeout("enableDiv()",1);
  };
  </script>
{% endblock content %}

TestInvest/perfiles/templates/perfiles/buy.html
{% extends "base.html" %}
{% load static  %}
{% block content %}
  <link rel="stylesheet" href="{% static 'css/buy.css' %}">
  <script src="{% static 'js/buy.js' %}"></script>
  {% if messages %}
     {% for message in messages %}
       <center>
         <h1>{{ message }}</h1>
       </center>
     {% endfor %}
  {% endif %}
  <div id="back0">
    <div id="back">
      <div id="container" class="container">
      {% if assets %}
        {% include 'perfiles/tab_price.html' %}
      {% else %}
        <h1 id="mj_not_assets">No hay activos disponibles para comprar</h1>
      {% endif %}
      </div>
    </div>
  </div>
  <div class="popup" id="myPopup">
    <form action="{% url 'buy' %}" method="POST" class="form"
      onsubmit="confirm(event, '{{virtual_money}}')" id="buy_form">
      <h2>Comprar Activo</h2>
      {% csrf_token %}
      {{ form.as_p }}
      <b id="total">Subtotal: $0</b><br>
      <b>Saldo disponible: ${{virtual_money}}</b><br><br>
      <center>
      <input id="accept" type="submit" value="Confirmar" class="btn"/>
      <input id="cancel" type="button" class="btn cancel" onclick="closePop()" value="Cancelar"/>
    </form>
    <div id="confirm">
     <b class="message"></b><br><br>
        <center>
       <button class="yes" onclick="success()">Si</button>&nbsp&nbsp
       <button class="no" onclick="window.location=url">No</button><br><br>
    <b id="time"></b>
    </div>
    <div class="popuptext" id="myForm_buy">
      <h4>El activo sera visible por otros jugadores</h4>
      <input id="accept" type="button" value="aceptar" onclick="enviar()">
    </div>
  </div>
  {% if mj == True %}
  <div id="back0">
    <div id="back">
      <div>
        <div class="popuptext" id="myPopup2">
          <h3 id="mj"></h3>
          <script>
            document.getElementById("myPopup").style.display = "none";
            document.getElementById("prices").style['pointer-events'] = 'none';
            $("#back").addClass('disable_background');
          </script>
       </div>
      </div>
    </div>
  </div>
<script>
  document.getElementById("mj").innerHTML =
  "Su compra del activo: " + localStorage.names +
  " por una cantidad de: " + localStorage.amounts +
  " a un precio total de: $" + localStorage.total_amount +
  " Fue un exito, su actual saldo en dinero liquido es: $" +
  '{{virtual_money}}' + "." +
  '<br><br><center class="form"><input type="button" class="btn cancel" onclick="send_to_wallet()" value="Ver mi cartera"/>' +
  '&nbsp&nbsp<input type="button" class="btn" onclick="reload()" value="Continuar comprando"/></center>';
  function send_to_wallet() {
    window.location="http://localhost:8000/wallet";
  }
  function reload() {
    window.location="http://localhost:8000/buy";
  }
  {% endif %}
</script>
<script>
  document.getElementById("nameC").innerHTML = "Compra";
  var url="http://localhost:8000";
  $("#id_total_amount").change(function () {
    //para calcular el subtotal cuando se activa el scroll.
    var amount = $("#id_total_amount").val();
    var total = amount * localStorage.sell;
    document.getElementById("total").innerHTML = "Subtotal $" + total;
  });
  $("#id_total_amount").keyup(function () {
    //para calcular el subtotal cuando se escribe un valor.
    var amount2 =  $(this).val();
    var total2 = amount2 * localStorage.sell;
    document.getElementById("total").innerHTML = "Subtotal $" + total2;
  });
  function put_values_on_the_form() {
    //put_values_on_the_form: Completa el formulario de acuerdo a lo elejido por el usuario y habilita la funcion enableDiv.
    document.getElementById("id_total_amount").value = "";
    document.getElementById("id_name").disabled = true;
    var value = JSON.parse(localStorage.value);
    var sell = value['sell'];
    var buy = value['buy'];
    localStorage.setItem('sell', sell);
    localStorage.setItem('buy', buy);
    document.getElementById("id_name").value = localStorage.name;
    setTimeout("enableDiv()",1);
  }
</script>
{% endblock content %}

TestInvest/perfiles/templates/perfiles/home.html
{% extends "base.html" %}

{% block title %}Bievenido{% endblock %}

{% block content %}
  <style>
    b {color:#0d7dc6;}
  </style>
    {% if user.is_authenticated %}
      <div align="center">
        <h1 color="blue">Invest Simulator</h1>
      </div>
      <center>
      <h2>Hola, {{ user.username }}</h2>
      <img src="{{ user.avatar.url }}" width="50px" height="50px" align="center"/>
      </center>
    {% else %}
      <div align="center">
        <h2><b>Bienvenido Invest Simulator</b>
        <br>para poder continuar puedes<br>
        <a href="{% url 'sign_up' %}">Registrarte</a> <br>o si ya tienes cuenta<br>
        <a href="{% url 'sign_in' %}">Inicia Sesión</a></a></h2></div>
    {% endif %}

{% endblock content %}

TestInvest/perfiles/templates/perfiles/login.html
{% extends "base.html" %}
{% block title %}Iniciar Sesión{% endblock %}
{% block content %}
  <center>
  <h2>Iniciar Sesión</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Iniciar Sesión</button>
    </form> <br><br>
    <h3>Para registrarse haga click
    <a href="{% url 'sign_up' %}"><b>Aqui</b></a></h3>
    <h3>Para volver al inicio haga click 
    <a href="{% url 'home' %}"><b>Aqui</b></a></h3>
{% endblock content %}

TestInvest/perfiles/templates/perfiles/price.html
{% extends "base.html" %}
{% block title %}Activos{% endblock %}
{% block content %}
<style>
 #prices {
    top:10%;
    left:35%;
  }
  .c {color:black; cursor: auto;}
</style>
  <title>Invest Simulator</title>
  {% if assets %}
     {% include 'perfiles/tab_price.html' %}
  {% else %}
    <center><h2 id="no_asset">No hay activos disponibles</h2></center>
  {% endif %}
{% endblock content %}

TestInvest/perfiles/templates/perfiles/profile.html
{% extends "base.html" %}

{% block title %}Bievenido{% endblock %}

{% block content %}
    <style>
    h1 {color:violet;}
    a1 {color:IndianRed;}
    .dropbtn {
      position:relative;left:5%;top:5px
    }
    </style>
    {% if user.is_authenticated %}
      <div align="center">
        <a href="{% url 'update_profile' %}">Editar perfil</a>
      </div>
      <div align="center">
        <h1 color="blue">Mi perfil</h1>
      </div>
      <center>
      <div>
        <h4>Nombre de usuario: {{user.username}}</h4>
        <h4>Nombre completo: {{user.first_name}}&nbsp{{user.last_name}}</h4>
        <h4>Email: {{user.email}}</h4>
        <h4>Avatar:</h4>
        <img src="{{ user.avatar.url }}" width="100px" height="100px" />
      </div>
    {% endif %}

{% endblock content %}

TestInvest/perfiles/templates/perfiles/salle.html
{% extends "base.html" %}
{% load static %}
{% block title %}Venta de Activo{% endblock %}
{% block content %}
<title>Venta de Activos</title>
<meta charset="utf-8">
<style type="text/css">
  body{ background-color:#EFF8FB; }
  .popup {margin-top: -14%; right:1%;}
  #container {
    position: relative;
    left:-3%;
  }
  .form .btn {width: 20%;}
  .form .cancel {width: 20%;}
</style>
 <script src="{% static 'js/salle.js' %}"></script>
 <font color="#030303" face="georgia" size="3"> 
<center>
<h1>Venta de activo</h1>
<h3  id="demo"></h3>
<script>
window.onload = function() {
    var valor = comprobar();
    document.getElementById("demo").innerHTML = "La cantidad de activos disponibles de " + valor.nombre + " es : " + valor.cant;
};
</script>
<div id="back0">
  <div id="back">
    </div>
  </div>
<div id="container">
  <form action="" method="Post" name="formu" id="formu" onsubmit="return false;" class="form">
    <br>Tu cantidad: <br><input required type="number" id="num" name="cantidad" value="" min="1"pattern="^[1-9]\d*$"><br></br>
    <input type="button" class="btn" onclick="openForm({{virtual_money}})" value="Confirmar"/>
    <input type="button" class="btn cancel" onclick="window.location='{% url 'wallet' %}'" value="Volver"/>
  </form>
</div>
<div class="popup" id="myForm">
    <form method="POST" class="form" onsubmit="Respuesta({{virtual_money}})" id="form">{% csrf_token %}
    <h1>RESUMEN</h1>
      {{ form.as_p }}
    <p>Estas seguro de realizar esta operacion?</p>
    <input id="accept" type="submit" class="btn" value="Si"/>
    <input type="button" class="btn cancel" onclick="closePop()" value="No"/>
  </form>
</div>
{% endblock content %}

TestInvest/perfiles/templates/perfiles/tab_price.html
<div id="prices">
<center><h2 id="nameC">Cotizaciones</h2><br></center>
<table id="tab">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Valor de Compra</th>
      <th>Valor de Venta</th>
      <th>Tipo</th>
    </tr>
  </thead>
  <tbody>
  {% for keys, values in assets %}
    <tr>
      <td><c class="c" onclick="openForm({{ values }}, {{ keys }})">
          {{ keys.1 }}</c></td>
      <td>{{ values.buy }}</td>
      <td>{{ values.sell }}</td>
      <td>{{ keys.0 }}</td>
    </tr>
  {% endfor %}
  </tbody>
</table>
</div>